### ISSUE TITLE
Improve the interface for selecting relevant products and topics for a KB article

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1945] opened 2024-08-08 23:23 UTC
The current interface for selecting relevant products and topics for a KB article -- used when either creating a new KB article or editing a KB article's metadata -- has several problems:
- Redundant selection. The user first selects one or more products, and then has to again find the appropriate product headings under which to select one or more topics. Since the topics are organized under specific product headings, the selection of a topic already implies a product.
- The user is allowed to select topics that do not exist for any of the products they've previously selected.

This ticket is to find a way to incrementally improve the interface by avoiding the problems identified above without taking on a more significant interface re-design.

**Comment by akatsoulas** [comment] 2024-09-09 12:05
PR https://github.com/mozilla/kitsune/pull/6221

**Comment by emilghittasv** [comment] 2024-09-30 09:33
Exploratory & regression testing activities are done for this ticket. 

I can confirm that:
* Choosing a particular product or topic automatically disables the selection of topics or products which are not relevant to the chosen topic or product.
* Choosing a particular product or topic automatically disables the selection of other products or topics which don't share a common product or topic. 
* Further increasing the selected products or topics count can disable additional topics & products automatically since those are not sharing a common topic or product. 
* Selecting a particular product will make the "Disabled products are not available given the selections" string appear and the "{x} selected" counter successfully increments or decrements depending on the selections/deselection.
* Selecting a particular topic will make the "Disabled topics are not available given the selections" string appear and the "{x} selected" counter successfully increments or decrements depending on the selections/deselection.
* The "Clear" option (for both products and topics) will successfully reset all the performed selections. 
* Archiving a topic will successfully remove the topic from the "Select topic" list.
* The change of unlinking a product from a particular topic is successfully reflected inside the kb/new and /metadata edit new UI by no longer being able to check the unlinked product and topic at the same time. 
* Adding a new product link to a particular topic is successfully reflected inside the kb/new and /metadata edit new UI by being able to check both the topic and product at the same time.
* Archiving a product will successfully remove the product from "Select product(s)" section in both the kb/new and /metadata edit page.

During the verification of this ticket the following issues were encountered: https://github.com/mozilla/sumo/issues?q=is%3Aopen+is%3Aissue+1968+1969+1970+1971

I'm moving this ticket inside the `release` column.

**Closed as completed** 2024-10-03 09:11 UTC
