### ISSUE TITLE
Remove archived docs from featured list

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1339] opened 2023-06-16 11:31 UTC
Right now we allow archived KB document to de displayed as featured. We should remove from that list any document that's archived

**Comment by emilghittasv** [comment] 2023-06-19 07:44
@akatsoulas 

I retested this today and noticed that the Obsolete-marked articles are still displayed in the "Featured Articles" section.

![obsolete](https://github.com/mozilla/sumo/assets/28087895/79515db3-7321-465a-adaf-ce21d0a93ebf)

In order to reproduce this access the:

https://support.allizom.org/en-US/products/firefox page and refresh it until the "Get started with Firefox-An overview of the main features" article (which is marked as obsolete) is displayed.

https://support.allizom.org/en-US/questions/new/desktop and refresh it until the "Search based on one word part three" article (which is marked as obsolete) is displayed.

**Comment by emilghittasv** [comment] 2023-06-27 07:59
Moving this ticket back to the **In Progress** column.

**Comment by akatsoulas** [comment] 2023-07-20 11:57
New PR opened here https://github.com/mozilla/kitsune/pull/5584

**Comment by emilghittasv** [comment] 2023-07-24 09:42
@akatsoulas 

This issue seems to be partially fixed now. The obsolete marked articles are no longer displayed inside the "Featured Articles" section inside the product support pages. 

From what I've noticed the obsolete marked articles are still displayed inside the "Featured Articles" section inside the product solutions page (see "Search based on one word part two" and "Search based on one word part three" articles from the https://support.allizom.org/en-US/questions/new/desktop page)

https://github.com/mozilla/sumo/assets/28087895/ddab3810-8f5a-4bbf-a44d-f94fd48b08aa

Tasos, would you like to keep this ticket open for the still reproducible part or would you prefer having a new ticket filled ?

**Comment by emilghittasv** [comment] 2023-07-25 14:18
During my 1-1 with Tasos this morning, we discovered that those featured articles displayed inside the product solutions pages (which were not removed after being obsolete-marked) were in fact pinned articles. After removing them from the pinned articles list (via the admin panel) they were no longer displayed inside that list.

I'm marking this ticket as ready for release.

**Closed** 2023-07-26 14:52 UTC
Labels: bug
