### ISSUE TITLE
[GA4] update GA events to use GA4 structure

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1646] opened 2024-01-17 07:52 UTC

**Comment by akatsoulas** [comment] 2024-02-06 17:22
This is a placeholder. Will be replaced by more specific issues

**Comment by emilghittasv** [comment] 2024-04-08 07:51
QA activities are finalized for the GA4 work in `stage`.

The following issues were encountered and reported:
**Still open/reproducible**:
https://github.com/mozilla/sumo/issues/1695
https://github.com/mozilla/sumo/issues/1696
https://github.com/mozilla/sumo/issues/1697

^ These issues are related to the Switching Devices KB article and are not caused by this GA work (those issues were reproducible with GA3 as well).

**Issues closed**:
The following issues were closed without a fix attached due to various reasons: 
https://github.com/mozilla/sumo/issues/1693 (Not an issue)
https://github.com/mozilla/sumo/issues/1700 (Issue was intermittent. Closed as no longer reproducible)
https://github.com/mozilla/sumo/issues/1718 (Valid issue but this won't cause problems with our GA funnels setup)
https://github.com/mozilla/sumo/issues/1719 (Valid issue but this won't cause problems with our GA funnels setup)

**Issues fixed & verified**:
The following issues were fixed & verified in stage:
https://github.com/mozilla/sumo/issues/1694 (Verified fixed in stage)
https://github.com/mozilla/sumo/issues/1698 (Verified fixed in stage)
https://github.com/mozilla/sumo/issues/1703 (Verified fixed in stage)
https://github.com/mozilla/sumo/issues/1704 (Verified fixed in stage)

I'm moving this ticket inside the `release` column.

**Closed as completed** 2024-04-10 16:33 UTC
