### ISSUE TITLE
The wizard's fxa-root attribute (sometimes?) gets emptied when the article content is updated and review-approved

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1326] opened 2023-05-30 16:27 UTC
**Describe the bug**
Stumbled on this today after updating the content of the Switching devices article. The fxa-root got emptied and I was unable to initiate the FxA sign in flow through the Wizard.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices
2. Edit the article and approve the revision.
3. Notice the fxa-root wizard attribute value.

**Expected behavior**
The fxa-root value is https://accounts.stage.mozaws.net

**Actual behavior**
The fxa-root value is empty.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment] 2023-06-01 19:34
@emilghittasv Wow, this one is baffling. This has happened to me, and I've seen it happen to at least one other person as well, but I can't reproduce it locally or on stage. I'm struggling to even develop a theory as to how it might be happening.

**Comment by escattone** [comment] 2023-06-01 19:55
I should note that we've never seen this happen in production.

**Comment by escattone** [comment] 2023-06-22 18:27
Closing this because we've not been able to reproduce it.

**Closed by escattone** 2023-06-22 18:27 UTC
Labels: bug, fidefe-device-migration
