### ISSUE TITLE
Create a MVP for a moderation tool.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1928] opened 2024-08-05 16:12 UTC
Users that have the permissions to moderate a thread should be able to moderate/approve whether a question in the AAQ belongs in the right topic under the new taxonomy.

In the first iteration:
- [x] All Topics of the new taxonomy will be listed in a drop-down
- [x] All Questions submitted for all products that have a forum will automatically be added in the queue
- [x] Users that can moderate a thread will be able to update the Topic

**Comment by akatsoulas** [comment] 2024-09-25 09:18
PR https://github.com/mozilla/kitsune/pull/6234

**Comment by emilghittasv** [comment] 2024-10-01 08:03
Functional and regression testing is finalized for this ticket.
* Users are able to flag content as "Spam or other unrelated content", "Inappropriate language/dialog", "Misplaced bug report or support request", "Abusive content" and "Other (please specify)".
* The correct information is displayed inside the flag ticket header for all flagged content in the format of "Flagged {content. ex questions} | {content. ex question} (Reason: {chosen flag reason}).
* The correct information is displayed for all flagged tickets (Flagged reason, comments made by the reporter, flagged item title or content, the creation date and author of the flagged content and the flag creation date and author)
* Depending on the user permissions and the flagged content, the "View", "Edit" and "Delete" buttons are displayed and functional.
* If the flagged content is a forum AAQ question and the reason is "Misplaced bug report or support request" the ticket contains an additional functionality of changing the topic of the flagged AAQ question.
* The "Current topic:" section successfully lists the current topic under which the flagged question is.
* The "Change Topic" dropdown contains the list of all IN_AAQ flagged topics related to the product under which the flagged question was filled.
* If topics are added or removed from the IN_AAQ via admin for a particular product this changes are reflected successfully inside the "Change Topic:" dropdown.
* The topic for the AAQ question changes immediately after selecting a different topic from the "Change Topic:" dropdown.
* Changing the topic via the "Change Topic" dropdown automatically updates the "Update Status" to "Redirected support request." and the "Update" button is enabled.
* The "Update Status" content was successfully update to:

1. "Removed spam content." and "No spam found." for an item flagged as "Spam or other unrelated content"
2. "Corrected language" and "Language is appropriate" for an item flagged as "Inappropriate language/dialog"
3. "Redirected support request." and "Content is appropriately placed." for an item flagged as "Misplaced bug report or support request".
4. "Addressed abusive content." and "No abuse detected." for an item flagged as "Abusive content".
5. "Issue resolved." and "No issues found." for an item flagged as "Other (please specify)"

* Flagged items can be successfully filtered by all the available reasons inside the "Filter by reason" side nav dropdown menu.

During the verification of this ticket, the following issues were filled: https://github.com/mozilla/sumo/issues?q=is%3Aissue+is%3Aopen+1988+1987+1986+1983+1984+1991

The regression testing which targeted other flagged items (user profiles, article discussion threads, community forum threads, automatically flagged posts like external links, toll free and NANP numbers) did not yield any new regressions. 

Moving this ticket inside the `release` column.

**Closed as completed** 2024-10-03 09:11 UTC
