### ISSUE TITLE
Finalize the tabbed menu UI

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1286] opened 2023-05-15 12:04 UTC
Create the final version of the UI and the supported functionality for the tabbed menu.

* Articles that belong to any subtopic under `Save and Sync` will be displayed in the `View All` section
* The subtopic will be rendered as tabs in the menu
* No page reload

**Comment by emilghittasv** [comment] 2023-05-17 13:26
* I can confirm that the tabbed menu section is successfully displayed on the Switching Devices article and respects the proposed UI mockup.
* Clicking on the tabbed menu options is filtering articles based on that particular subtopic and no page reload occurs on click.
* Articles belonging to each tabbed menu category can be successfully accessed from the list (the article opens in the same tab)
* I can confirm that the tabbed menu automatically adds/displays the  newly added subtopics (under the Save and Sync parent topic) 
* Tabbed menu options can be navigated & accessed via keyboard-only operations.
* The verification was performed on both Firefox (Desktop & Mobile) & Chrome browsers.

During the verification of this ticket I encountered and filled:
* #1287 - which is a regression affecting the search result. This was verified fixed in stage.
* #1290 - bug which caused the article display inside the tabbed menu to break. This was verified fixed in stage.

Apart from the above fixed issues, the following tickets were filled:
* #1293 - Articles belonging to a Sync and Save subtopic are not displayed inside the "View All" tabbed menu option if, at creation time, both Sync and Save and the actual subtopic checkboxes were not checked (only the subtopic checkbox was checked).
* #1288 - The "Switching-devices" article is also displayed inside the "tabbed menu" list.
*  #1292  - Enhancement to consider removing the on-click border highlight for the "tabbed menu" options.
* #1291 - Enhancement to consider adding the pointer cursor on mouse-over for the "tabbed menu" options.
* #1289 - Enhancement to consider adding pagination to the displayed articles.

Since #1287 and #1290 were fixed and verified I have no objection in moving this ticket inside the "Ready for release" column.

**Closed** 2023-05-31 21:16 UTC
Labels: fidefe-device-migration
