### ISSUE TITLE
CSP error in Revision page

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1088] opened 2022-08-23 09:21 UTC
**Describe the bug**
CSP error throught Article revision sections.

**To Reproduce**
1. Go to https://support.allizom.org/en-US/kb/search-working-article-test/revision/139143
2. Inspect page and view Console
3. Reload for results.

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/53306802/186121670-ca22be7c-747f-40c1-b921-3f2cdfdc2cd7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 103.0.2

**Additional context**
Error Occurs throught the revision pages 
https://support.allizom.org/en-US/kb/search-working-article-test/history

**Comment by akatsoulas** [comment] 2022-08-30 14:16
@mirunacurtean I cannot reproduce this with my browser. Could this domain coming from a plugin you are using? Can you try without any plugins or in private mode?

**Comment by mirunacurtean** [comment] 2022-08-30 14:46
@akatsoulas True, I cannot reproduce this on a private window. 
![image](https://user-images.githubusercontent.com/53306802/187465968-995768c8-d2ad-4b41-b6ef-a42be56aa7bd.png)

Still, it continues to occur on Chrome and Firefox (where I don't use any plugins) and I tried with a new Fx profile too with the same results. 
![image](https://user-images.githubusercontent.com/53306802/187466287-0a659e61-a6c7-4ef3-9ce1-89c65b1d1f3a.png)

**Comment by akatsoulas** [comment] 2022-08-30 14:56
This is probably coming from an addon. Closing this issue

**Closed by akatsoulas** 2022-08-30 14:56 UTC
Labels: bug
