### ISSUE TITLE
Update the contributor tools sidenav in Locales

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1756] opened 2024-05-03 13:16 UTC
[Figma design](https://www.figma.com/file/T7fMC8k01Lrbp7zHknBvx3/Information-Architecture?type=design&node-id=749-7319&mode=design&t=Wo0SI3HQ9VIdBhea-4l)

**Comment by emilghittasv** [comment] 2024-05-09 13:36
@akatsoulas QA is currently blocked in testing this ticket due to https://github.com/mozilla/sumo/issues/1777

**Comment by emilghittasv** [comment] 2024-05-27 08:40
I can confirm that the `Contributor tools` side nav from the Locales page matches the Figma design in `dev`.

Leaving this ticket inside the `qa` column until the IA work is pushed & verified in `stage` as well.

**Comment by emilghittasv** [comment] 2024-06-07 07:48
I can confirm this in `stage` as well.

Moving this ticket inside the `release` column.

**Closed as completed** 2024-07-10 14:32 UTC
