### ISSUE TITLE
Restore bitly functionality to create shortlinks within the KB

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1065] opened 2022-07-05 15:15 UTC

**Comment by kelimuttu** [comment] 2022-08-09 09:13
I was asked by @mirunacurtean to test this functionality. There are a few things I'd like to clarify after I tested this: 
* I found that the link is locale-specific. I'm not sure if this was intended. The thing with this is that, contributors often share the shortened link to users, which may use a different locale. With regards to this scenario, it's actually better to use a locale-agnostic link so users will be directed to their preference locale automatically. This being said, this will require a different approach, which is, that we will have the same shortened link for the same article in different locales. 
* Regardless of the above point, I found that the current automation doesn't work for Indonesian locale. For example: [this article](https://support.allizom.org/id/kb/instalasi-firefox-pada-ipad-iphone-atau-ipod-anda) (for comparison, this is the same article for [de](https://support.allizom.org/de/kb/firefox-auf-dem-ipad-iphone-oder-ipod-installieren), [fr](https://support.allizom.org/fr/kb/installer-firefox-sur-ipad-iphone-ipod), or [ko](https://support.allizom.org/ko/kb/install-firefox-your-ipad-iphone-or-ipod)). I haven't tested all locales, but out of 15 locales that I tested, this only happen with id locale.

**Comment by mirunacurtean** [comment] 2022-08-09 09:21
Thank you @kelimuttu You've done in a very short time what I was trying to figure out on and off for a while. Do you know if this is that way it worked before? As noted in the title of this ticket, the purpose is to restore the bitly functionality present at some time in the past, and we need to understand if these are regressions or just new issues to tackle separately. 
CC @escattone  for awarness.

**Comment by kelimuttu** [comment] 2022-08-09 09:35
@mirunacurtean I'm not aware of how it was before. It's been a while since the automation was broken. But I can check with contributors who may know better than me.

**Comment by mirunacurtean** [comment] 2022-08-09 15:00
> @mirunacurtean I'm not aware of how it was before. It's been a while since the automation was broken. But I can check with contributors who may know better than me.

@kelimuttu Yes, please. That would be quite useful. The conversation thread can be linked in the ticket, after.

**Comment by mirunacurtean** [comment] 2022-08-09 16:45
> @mirunacurtean A contributor pointed me out to an [old bug](https://bugzilla.mozilla.org/show_bug.cgi?id=766394) which refer to [this PR](https://github.com/mozilla/kitsune/pull/2006) that seems useful for historical context. From what I can catch, at least there are two more requirements for this functionality:
> 
> * The automation should also work for new article (not sure if you have tested this)
> * KB articles that are part of the [“Admin” category](https://support.mozilla.org/en-US/contributors/kb-overview?category=40) should be exempted from this automation as they are meant to be accessed from an in-product link

@kelimuttu I can confirm the new article share link automation (which on stage had been deactivated the previous days and it also works by generating a links in 6 hour cycles) 
Test articles:
https://support.allizom.org/en-US/kb/share-article
https://support.allizom.org/en-US/kb/copy-paste

For the second point, I will create some test data this evening and hopefully it will ge good to check and to go by tomorrow morning. 

Thank you

**Comment by escattone** [comment] 2022-08-09 18:30
@kelimuttu @mirunacurtean Thanks so much for all of your work on this. I can confirm that the Bitly functionality was restored as it was in the past. In other words, the logic of generating short links did not change. So I think we should open one or more tickets with any new issues that were found.

One more thing. I did check the current code, and I see that we do **not** include the locale when generating the short link, so we'll have to look into that some more.

**Comment by mirunacurtean** [comment] 2022-08-10 07:05
> > @mirunacurtean A contributor pointed me out to an [old bug](https://bugzilla.mozilla.org/show_bug.cgi?id=766394) which refer to [this PR](https://github.com/mozilla/kitsune/pull/2006) that seems useful for historical context. From what I can catch, at least there are two more requirements for this functionality:
> > 
> > * The automation should also work for new article (not sure if you have tested this)
> > * KB articles that are part of the [“Admin” category](https://support.mozilla.org/en-US/contributors/kb-overview?category=40) should be exempted from this automation as they are meant to be accessed from an in-product link
> 
> @kelimuttu I can confirm the new article share link automation (which on stage had been deactivated the previous days and it also works by generating links in 6 hour cycles) Test articles:
> 
> 1. https://support.allizom.org/en-US/kb/share-article
> 2. https://support.allizom.org/en-US/kb/copy-paste
> 
> For the second point, I will create some test data this evening and hopefully it will be good to check and to go by tomorrow morning. Updating with new articles:
> 
> 1. https://support.allizom.org/en-US/kb/admin-article-test
> 2. https://support.allizom.org/de/kb/sprache-eingabe-erkennung
> 
> Thank you

Morning. I've verfied that these articles have/ or don't have shortlinks, as expected. 



> @kelimuttu @mirunacurtean Thanks so much for all of your work on this. I can confirm that the Bitly functionality was restored as it was in the past. In other words, the logic of generating short links did not change. So I think we should open one or more tickets with any new issues that were found.
> 
> One more thing. I did check the current code, and I see that we do **not** include the locale when generating the short link, so we'll have to look into that some more.

I've added this [new ticket](https://github.com/mozilla/sumo/issues/1082) for all the locale specific work, to be further discussed and defined. 

So with all that done, I'm marking this as Ready for Release.

**Comment by kelimuttu** [comment] 2022-08-10 09:08
> @kelimuttu @mirunacurtean Thanks so much for all of your work on this. I can confirm that the Bitly functionality was restored as it was in the past. In other words, the logic of generating short links did not change. So I think we should open one or more tickets with any new issues that were found.

Sounds good to me. 

@mirunacurtean I'd like to get some clarification about the issue that you just created. But let's talk more about that in https://github.com/mozilla/sumo/issues/1082

**Closed** 2022-08-16 11:54 UTC
Labels: bug
