### ISSUE TITLE
500 error is returned when trying to change some tags from the /admin/taggit/tag/ list

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#2084] opened 2024-12-02 14:32 UTC
**Steps to reproduce**
1. Go to /admin/taggit/tag/
2. Click on one of this listed tags: `2015`, `AoA`, `sumo AoA 2013`, `sumo forum 2015`, `sumo kb 2015`, `sumo l10n 2014` 

**Expected behavior**
The tags from step 2 are successfully accessible.

**Actual behavior**
500 is returned and sentry fires https://mozilla.sentry.io/issues/6047002268/?project=4504326797197312&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage`

**Comment by escattone** [comment] 2024-12-05 20:24
**This has been resolved in stage and production.**

This has been a bug in stage and production for a long time, since the removal of the `badger` app/package when it was replaced by the `kitsune.kbadge` app.

The root cause of this issue is that when a `taggit.Tag` is selected in the Django Admin, the tag's tagged items are also displayed, and all of the tags that returned a 500 error had one or more tagged items that were using the `badge` content tyoe -- a content type with `model="badge"` and `app_label="badger"`. That content type has been invalid since the `badger` app was removed long ago and replaced with the `kitsune.kbadge` app. That content type should have been replaced at that time with the `kbadge | badge` content type (`model="badge"` and `app_label="kbadge"`).

## Stage Resolution
In stage, I updated all of the `taggit.TaggedItem` and `kitsune.tags.models.SumoTaggedItem` instances with a `badge` content type to a `kbadge | badge` content type.

```python
In [1]: ct_badge = ContentType.objects.get(model="badge", app_label="badger")
In [2]: ct_badge
Out[2]: <ContentType: badge>
In [3]: ct_kbadge = ContentType.objects.get(model="badge", app_label="kbadge")
In [4]: ct_kbadge
Out[4]: <ContentType: kbadge | badge>
In [5]: TaggedItem.objects.filter(content_type=ct_badge).count()
Out[5]: 62
In [6]: SumoTaggedItem.objects.filter(content_type=ct_badge).count()
Out[6]: 62
In [7]: for b in Badge.objects.filter(pk__in=TaggedItem.objects.filter(content_type=ct_badge).values_list("object_id", f
    ...: lat=True)).all():
    ...:     print(b)
    ...:
2015 Support Forum Badge
2015 Army of Awesome Badge
2015 KB Badge
2015 L10n Badge
2014 Army of Awesome Badge
2014 L10n Badge
2014 KB Badge
2014 Support Forum Badge
2012 Army of Awesome Badge
2013 Army of Awesome Badge
2010 Army of Awesome Badge
2011 Army of Awesome Badge
2012 Support Forum Badge
2010 KB Badge
2010 L10n Badge
2010 Support Forum Badge
2011 KB Badge
2011 L10n Badge
2011 Support Forum Badge
2012 KB Badge
2013 KB Badge
2013 L10n Badge
2013 Support Forum Badge
2012 L10n Badge
In [8]: SumoTaggedItem.objects.filter(content_type=ct_badge).update(content_type=ct_kbadge)
Out[8]: 62
In [9]: TaggedItem.objects.filter(content_type=ct_badge).update(content_type=ct_kbadge)
Out[9]: 62
In [10]: TaggedItem.objects.filter(content_type=ct_badge).count()
Out[10]: 0
In [10]: SumoTaggedItem.objects.filter(content_type=ct_badge).count()
Out[10]: 0
```

## Production
In production, I updated all of the `taggit.TaggedItem` instances with a `badge` content type to a `kbadge | badge` content type. That's all that is needed, because when the `kitsune/tags/migrations/0002_auto_20241115_0241.py` migration is run during the release next week, all of the `kitsune.tags.models.SumoTaggedItem` instances will be created from the `taggit.TaggedItem` instances, and therefore pick-up the updated content type.

```python
In [1]: ct_badge = ContentType.objects.get(model="badge", app_label="badger")
In [2]: ct_badge
Out[2]: <ContentType: badge>
In [3]: ct_kbadge = ContentType.objects.get(model="badge", app_label="kbadge")
In [4]: ct_kbadge
Out[4]: <ContentType: kbadge | badge>
In [5]: TaggedItem.objects.filter(content_type=ct_badge).count()
Out[5]: 96
In [6]: TaggedItem.objects.filter(content_type=ct_kbadge).count()
Out[6]: 0
In [7]: for b in Badge.objects.filter(pk__in=TaggedItem.objects.filter(content_type=ct_badge).values_list("object_
    ...: id", flat=True)).all():
    ...:     print(b)
    ...:
2015 Support Forum Badge
2015 Army of Awesome Badge
2015 KB Badge
2015 L10n Badge
2014 Army of Awesome Badge
2014 L10n Badge
2014 KB Badge
2014 Support Forum Badge
2012 Army of Awesome Badge
2013 Army of Awesome Badge
2010 Army of Awesome Badge
2011 Army of Awesome Badge
2012 Support Forum Badge
2010 KB Badge
2010 L10n Badge
2010 Support Forum Badge
2011 KB Badge
2011 L10n Badge
2011 Support Forum Badge
2012 KB Badge
2013 KB Badge
2013 L10n Badge
2013 Support Forum Badge
2012 L10n Badge
In [8]: TaggedItem.objects.filter(content_type=ct_badge).update(content_type=ct_kbadge)
Out[8]: 96
In [9]: TaggedItem.objects.filter(content_type=ct_badge).count()
Out[9]: 0
```

**Comment by emilghittasv** [comment] 2024-12-06 09:38
I can confirm this in `stage`.

Thanks @escattone for the detailed information!!

Moving this ticket inside the `release` column.

**Closed as completed** 2024-12-09 17:07 UTC
Labels: bug
