### ISSUE TITLE
Error in console when loading Mozilla VPN Support page

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1716] opened 2024-04-04 15:49 UTC
**Describe the bug**
VPN QA reports seeing a console error when loading the VPN support landing page.

**Preconditions**
Have Firefox installed on your desktop device.

**Steps to reproduce**

1. Open the page https://support.mozilla.org/en-US/products/firefox-private-network-vpn
2. Check the console;
3. Observe the error in the console

**Expected behavior**
No errors appear in the console.

**Actual behavior**
Uncaught TypeError: e is undefined" error appears in the console.

**Screenshots/Screencasts**
![SUMOVPNerror](https://github.com/mozilla/sumo/assets/87725469/1985c3f5-924d-43d5-8768-b526b92c1d29)

**Desktop (please complete the following information):**
 - OS: Mac OS 14.3.1, Window 10
 - Browser: Firefox
 - Version: 123.0.1, 124.0.2

**Additional context**
Was able to reproduce on Mac OS and Windows Devices. Couldn't test on mobile.

**Comment by escattone** [comment] 2024-07-23 23:36
This is caused by sloppy JS code in our `products.js` file that doesn't check if [latestVersion](https://github.com/mozilla/kitsune/blob/99d6154cca3ab5768b08c61239ec5c04f36ea01f/kitsune/sumo/static/sumo/js/products.js#L8) is defined. The fix is super simple. I'll have a PR ready tomorrow morning, which will also include converting `products.js` to vanilla JS that doesn't depend on jQuery.

**Comment by emilghittasv** [comment] 2024-07-25 09:38
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.

**Closed as completed** 2024-09-04 15:20 UTC
Labels: bug
