### ISSUE TITLE
Troubleshooting topic has persistent subtitle unrelated to all products

### ISSUE THREAD

**Issue by JC-Support** [mozilla/sumo#1867] opened 2024-07-08 16:52 UTC
There is a subtitle underneath the Troubleshooting topic title, that says " Troubleshoot issues for Private Network " regardless of what product is selected. 

Steps to reproduce:
1. Visit support.mozilla.org
2. Mouse over Explore help articles
3. Select "Troubleshooting" topic
4. Cycle through products from drop down menu on the right hand side of the screen
5. Observe: Subtitle is persistent regardless of what product is selected

![2024-07-08_11-48-04 (1)](https://github.com/mozilla/sumo/assets/87725469/87309e48-46db-45a1-9db0-52bcbea1726e)

**Comment by emilghittasv** [comment] 2024-07-08 20:28
Interesting!

This issue is not reproducible in `stage`. Only `prod` seems to be affected.

**Comment by akatsoulas** [comment] 2024-07-09 08:56
This is now fixed in prod. I will follow up with the content team in case we need to update the wording

**Closed as completed by akatsoulas** 2024-07-09 08:56 UTC
