### ISSUE TITLE
Localized articles lack topic in breadcrumbs

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo#813] opened 2021-03-30 09:10 UTC
Localized articles don't show their topic in their breadcrumbs. Compare https://support.mozilla.org/en-US/kb/get-started-firefox-overview-main-features:

![Screenshot_2021-03-30 Get started with Firefox - An overview of the main features Firefox Help](https://user-images.githubusercontent.com/755354/112964194-01db0f00-9140-11eb-9d2f-bf6d1b0a290b.png)

with https://support.mozilla.org/de/kb/erste-schritte-mit-firefox:

![Screenshot_2021-03-30 Erste Schritte mit Firefox – Überblick über die wichtigsten Funktionen Hilfe zu Firefox](https://user-images.githubusercontent.com/755354/112964193-01db0f00-9140-11eb-8e3c-801beaf06525.png)

or https://support.mozilla.org/fr/kb/debuter-firefox-apercu-fonctionnalites-principales:

![Screenshot_2021-03-30 Débuter avec Firefox – aperçu des fonctionnalités principales Assistance de Firefox](https://user-images.githubusercontent.com/755354/112964190-01427880-9140-11eb-9c46-c6e7842a0501.png)

**Comment by akatsoulas** [comment] 2023-09-11 14:46
Duplicate of #1312

**Closed by akatsoulas** 2023-09-11 14:46 UTC
Labels: bug
