### ISSUE TITLE
Profile image/avatar not removed after deleting account

### ISSUE THREAD

**Issue by ghost** [mozilla/sumo#2011] opened 2024-10-20 17:10 UTC
**Describe the bug**

I've deleted my SUMO account, but my profile image/avatar is still visible next to my posts.

**Steps to reproduce**
1. Upload a profile image
2.  Make some edits in articles or post comments in discussions
3. Delete your account

**Expected behavior**
Since a user can be identified by its avatar (which might as well be a personal photo), it should be deleted too as soon as an account is deleted.

**Actual behavior**
 
My profile image is still visible next to my comments: [edited] . Please delete it.

**Comment by akatsoulas** [comment] 2024-10-21 12:38
The avatar for this case was manually deleted.
I also opened PR https://github.com/mozilla/kitsune/pull/6301 to deal with this issue in a more permanent base.

Thank you for filing this bug

**Comment by emilghittasv** [comment] 2024-10-23 10:41
I can confirm that this issue is verified fixed in `stage`.

The profile avatar is successfully removed after deleting the SUMO account.

During the verification of this ticket I've noticed that a new regression was introduced: https://github.com/mozilla/sumo/issues/2015

I'm moving this particular ticket inside the `release` column.

**Comment by akatsoulas** [comment] 2024-10-23 15:20
New PR to address this issue
https://github.com/mozilla/kitsune/pull/6309

**Comment by emilghittasv** [comment] 2024-10-24 07:59
@akatsoulas I can confirm that with the new PR the SUMO avatar is successfully removed at profile deletion.

Unfortunately the regression mentioned in https://github.com/mozilla/sumo/issues/2015 is still reproducible in `stage`.

**Comment by emilghittasv** [comment] 2024-10-24 08:49
It turned out that https://github.com/mozilla/sumo/issues/2015 is not a regression caused by this change.

**Closed as completed** 2024-10-31 07:07 UTC
Labels: bug
