### ISSUE TITLE
[Wagtail] Introduce Wagtail such that it could be used for the products landing page

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1728] opened 2024-04-16 14:59 UTC
Introduce and configure Wagtail for our Django environment. For now, we'd like to use it for experimentation and the products landing page.

Wagtail expects Django templates for it's admin pages, but we'd like to use Jinja for all of our current pages as well as for the rendering of the content of Wagtail pages. Configure our templates to handle this.

**Comment by akatsoulas** [comment] 2024-04-30 08:47
Closing as duplicate of #1681

**Closed as completed by akatsoulas** 2024-04-30 08:47 UTC
