### ISSUE TITLE
Disable GraphQL introspection in our instances

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1362] opened 2023-07-11 17:26 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1841772

**Comment by escattone** [comment] 2023-07-24 22:53
## QA Notes
Unfortunately, this can't be tested on stage, because the code only disables introspection in production. So we can consider this good to go. Once this has been deployed, we should test in production using the following:

```sh
curl -X POST https://support.mozilla.org/graphql -H 'Content-Type: application/json' -d '{"query": "query { __schema { types { name } } }"}'
```

**Comment by emilghittasv** [comment] 2023-07-25 12:00
Thanks Ryan! I'll take a look when this gets released to prod and leave a comment with the results.

**Comment by emilghittasv** [comment] 2023-07-27 11:21
I can confirm that this is fixed in production.

When executing the `curl -X POST https://support.mozilla.org/graphql -H 'Content-Type: application/json' -d '{"query": "query { __schema { types { name } } }"}'` command the output is: `{"errors":[{"message":"GraphQL introspection is disabled.","locations":[{"line":1,"column":9}],"path":["__schema"]}],"data":null}%  ` 

Closing this ticket.

**Closed** 2023-07-27 11:21 UTC
