### ISSUE TITLE
Profile language defaults to English in Zendesk in the case of non-Latin languages

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#954] opened 2021-10-08 08:48 UTC
**Environment:**
Stage

**Precondition:**
Ability to view results in Zendesk

**Steps to reproduce:** 
1. Create an account that has a non-English language like Chinese, Japanese, Arabic or update the account profile language to one of those. 
![image](https://user-images.githubusercontent.com/53306802/136526199-ce8e3cc7-884c-4f5b-aad0-b642d51270fe.png)

2. Go through the Mozilla AAQ flow and get to the Contact Support form. 
3. Submit a ticket. 
4. In Zendesk, view the ticket and check the user's language. 

**Expected result:** 
When submitting tickets for Latin alphabet languages, the profile language is rendered correctly in Zendek (for example, Spanish or French) 
![image](https://user-images.githubusercontent.com/53306802/136526831-26af836d-e003-4181-a286-7073145b309a.png)

**Actual result:** 
Language in Zendesk shows as English, instead of Japanese. 
![image](https://user-images.githubusercontent.com/53306802/136526923-082d07f2-6867-486a-9df5-9d562697a8e4.png)

**Comment by emilghittasv** [comment] 2023-03-29 11:40
I am unable to reproduce this issue anymore.

Changing my profile's "Preferred language" and submitting a Zendesk ticket successfully updates the language in Zendesk.

Japanese example:

![image](https://user-images.githubusercontent.com/28087895/228524220-359f695d-1f33-4084-80c7-1146200df406.png)


Closing this for now. Feel free to re-open if this issue is still reproducible

**Closed as completed by emilghittasv** 2023-03-29 11:40 UTC
Labels: bug
