### ISSUE TITLE
Non-English locales are showing English content

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo#1135] opened 2022-11-03 08:10 UTC
**Describe the bug**
Visiting SUMO in non-English locales are still showing English. 

**To Reproduce**
1. Go to any non-English locale, for example [ID](https://support.mozilla.org/id/) or [FR](https://support.mozilla.org/fr/)

**Expected behavior**
Page is showing up in Indonesian or French

**Additional context**
Contributors indicate in our Matrix room that this issue was new.

**Comment by markh-bz** [comment] 2022-11-04 10:35
Please note that localized help articles are displayed in the correct locale, but all SUMO stuff (landing pages, menus, TOC in articles, etc.) is in English.

**Comment by escattone** [comment] 2022-11-04 14:49
Thanks for reporting this. I'll look into this today.

**Comment by escattone** [comment] 2022-11-04 21:22
The event that started the ball rolling towards breaking `gettext` calls on the server side was the merge of https://github.com/mozilla/kitsune/pull/5283, but the root cause is something else. Here's a timeline of events and explanations:

- https://github.com/mozilla/kitsune/pull/5283 merged about 4 days ago
- That PR added the two message strings `"Improve our help articles"` and `"Answer questions in the support forum"`
- Both of those messages already existed within all of the existing `django.po` files as [obsolete messages](https://www.gnu.org/software/gettext/manual/html_node/Obsolete-Entries.html) -- which are no-longer used messages commented-out with `#~` and saved for the convenience of being able to resurrect their translation if added back later
- 2 days ago, via https://github.com/mozilla-l10n/sumo-l10n/pull/106, `babel` was used to extract and merge those two strings into every locale's `django.po` file. `babel` was smart too. It found the obsolete messages, and resurrected their saved translations when creating the new messages, but it **did not remove the obsolete messages**, which I think it should have. `puente`, a deprecated package we were using until we switched to `python-babel` just this week, runs the `msgmerge` command when merging, while `babel` seems to run its own code. That may be the root cause of the issue.
- From that moment onward, when building the production Docker image, every locale's `django.po` file fails to compile because those two messages include an active message as well as a commented-out obsolete message -- not sure why `msgfmt` considers the [commented-out obsolete messages as active entries but it does](https://www.gnu.org/software/gettext/manual/html_node/Obsolete-Entries.html) -- so no [django.mo](http://django.mo/) files are included in the final Docker image, which in turn means that the server-side `gettext` calls don't find any translations. The `django.po` files are linted and compiled in every build of the production docker image via the `scripts/l10n-fetch-lint-compile.sh` script and although the `dennis-cmd` finds no errors when linting the `django.po` files, the actual compilation using the `msgfmt` command fails, for example:
```sh
Linting and compiling ./de/LC_MESSAGES/django.po...
./de/LC_MESSAGES/django.po:14062: duplicate message definition...
./de/LC_MESSAGES/django.po:8415: ...this is the location of the first definition
./de/LC_MESSAGES/django.po:14080: duplicate message definition...
./de/LC_MESSAGES/django.po:8410: ...this is the location of the first definition
msgfmt: found 2 fatal errors
```

**Comment by escattone** [comment] 2022-11-08 23:28
This should be fixed once we deploy our release tomorrow. Thanks for your patience everyone!

**Comment by escattone** [comment] 2022-11-09 17:46
This is resolved. Thanks again @kelimuttu for reporting this, and to everyone for their patience while we worked through the complexity of this.

**Closed by escattone** 2022-11-09 17:46 UTC
Labels: bug

**Comment by kelimuttu** [comment] 2022-11-09 17:55
Thanks to you and the team for a quick turnaround on this. (:
