### ISSUE TITLE
The products listed inside the "Browse all product support forums" are arranged differently than prod

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1589] opened 2023-11-21 16:39 UTC
**Steps to reproduce**
1. Navigate to the https://support.allizom.org/en-US/questions/ page

**Expected behavior**
The products are arranged similar to `prod`

**Actual behavior**
`Firefox Support Forum` swapped positions with `Firefox for iOS Support Forum`

**Screenshots**
**Stage**
![image](https://github.com/mozilla/sumo/assets/28087895/19296965-1965-4202-8d23-5396ed9d84c3)

**Prod**
![image](https://github.com/mozilla/sumo/assets/28087895/0bceb5dd-9353-437b-9080-28b582202cf2)

**Desktop:**
 - OS: Windows
 - Browser: Firefox

**Additional context**
Reproducible in `stage`.

**Comment by escattone** [comment] 2023-11-21 23:54
I've confirmed that this is not an issue with Postgres, but simply an allowed variation based on the `display_order`, since all three of the products in the first row of tiles share the same value of `1` in both production and stage. We should probably set the `display_order`for each of those first three products in production to the explicit value desired, but that will mean adjusting the `display_order` values for many of the other products to make room for more numbers while maintaining the relative order of the products.

## Current Display Order

<img width="710" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/8e68bd0e-e765-4273-9d8b-952e67902fe4">

## Proposed Display Order

<img width="884" alt="image" src="https://github.com/mozilla/sumo/assets/3743693/473b3d7c-30ae-4e68-8c1b-7e98edb4e303">

**Comment by akatsoulas** [comment] 2023-11-22 11:49
We can adjust the display order on the fly in prod if/when needed. I am closing this issue since this is not a bug

**Closed as completed by akatsoulas** 2023-11-22 11:49 UTC
Labels: bug

**Comment by escattone** [comment] 2023-12-18 15:38
This has been fixed on stage and prod.
