### ISSUE TITLE
KB article visits count is not accurate

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1994] opened 2024-10-01 12:05 UTC
**Describe the bug**
Our trusted contributors have reported that the "Visits" numbers inside the KB dashboard are incorrect.

**Steps to reproduce**
1. Go to https://support.mozilla.org/en-US/contributors
2. Interact with the "Last 7 days", "Last 30 days", "Last 90 days" and "Last Year" filters.

**Expected behavior**
The "Visits" numbers are correct.

**Actual behavior**
The "Visits" numbers don't look accurate.

**Desktop :**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `prod`.

**Comment by emilghittasv** [comment] 2024-10-01 12:05
Bug fix candidate for current sprint.

**Comment by akatsoulas** [comment] 2024-10-01 12:10
Duplicate of https://github.com/mozilla/sumo/issues/1896

**Closed as completed by akatsoulas** 2024-10-01 12:10 UTC
Labels: bug
