### ISSUE TITLE
500 error when navigating to /questions/firefox, /questions/mobile and questions/all pages

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1919] opened 2024-07-30 08:34 UTC
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/firefox, https://support.allizom.org/en-US/questions/mobile and https://support.allizom.org/en-US/questions/all pages.

**Expected behavior**
The `Firefox`, `Firefox for Android` and `All Products Community Forum` community forums are successfully displayed.

**Actual behavior**
500 error and sentry fires https://mozilla.sentry.io/issues/5655154181/?project=4504326797197312&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 
**Additional context**
* https://support.allizom.org/en-US/questions/ios, https://support.allizom.org/en-US/questions/focus-firefox, https://support.allizom.org/en-US/questions/firefox-enterprise and https://support.allizom.org/en-US/questions/thunderbird are not affected.
* This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment] 2024-07-31 10:57
This is duplicate of #1920 . I am moving this under QA in order to verify that the issue is no longer reproducible after the fix for #1920

**Comment by emilghittasv** [comment] 2024-08-01 11:35
I can confirm that this issue is verified fixed in `stage`.

Moving this ticket inside the `release` column.

**Closed as completed** 2024-09-04 15:17 UTC
Labels: bug
