### ISSUE TITLE
Firefox Accounts Footer Navigation

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1472] opened 2023-09-12 16:22 UTC
Footer navigation updated for Mozilla Accounts.

**Comment by smithellis** [comment] 2023-09-13 13:21
https://github.com/mozilla/kitsune/pull/5645

**Comment by emilghittasv** [comment] 2023-09-20 10:29
I can confirm, on a locally built build that the "Firefox Accounts" footer option was renamed to "Mozilla Accounts" and it also contains the following options:

* Sign In/Up
* What is it? 
* Reset Password
* Sync My Data
* Get Help

Since this change lives inside the mozilla-accounts branch for now, I'm closing this ticket instead of moving it inside the "Release" column.

**Closed by emilghittasv** 2023-09-20 10:29 UTC
