### ISSUE TITLE
InconsistentMigrationHistory error in Sentry

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1336] opened 2023-06-14 14:38 UTC
The PR that normalized the squashed migrations produced the following error in Sentry
https://mozilla.sentry.io/issues/4250565154/

**Comment by escattone** [comment] 2023-06-22 18:41
This turned out to be caused by the `manage.py migrate` commands silently failing on stage and prod (they worked locally) ever since [this change](https://github.com/mozilla/kitsune/pull/5418) was merged. We had no notifications of the failed migrations, so we assumed the migrate commands were working when they weren't. So this error occurred because `kbforums.0001_initial` was "normalized" to depend upon `wiki.0001_squashed_0013_alter_document_related_documents_and_more`, because we assumed it had already been applied, but it hadn't been.

**Closed by escattone** 2023-06-22 18:41 UTC
Labels: bug
