### ISSUE TITLE
Question with more than one line of symbols as content causes layout issues in search results

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#549] opened 2020-07-21 17:16 UTC
**Environment:** 
Production 
Stage

**Platform tested on:**
Windows 10

**Precondition:** 
Sign in and add a question with more than one line of symbols in the description (How can we help? field)

**Steps to reproduce:**

1. Go to https://support.mozilla.org/en-US/ and pick Firefox Accounts popular searches option. 
2. Select Community Discussion Only.
3. View questions.

**Expected results:**
Question layout is restricted to search result space in search results. 

**Actual Results:**
Question layout overlaps 'Filter by product' section. 
![image](https://user-images.githubusercontent.com/53306802/88085277-4fa17f80-cb8e-11ea-8f85-8bc3d80e8699.png)

Note:  Reproduced in stage as well by adding https://support.allizom.org/en-US/questions/1207101
In product support forum the layout issue does not occur. ex: https://support.allizom.org/en-US/questions/firefox?show=responded

**Comment by emilghittasv** [comment] 2023-03-29 14:53
I am unable to reproduce this issue (maybe it got fixed along the way?). The questions which contain more than one line of symbols no longer overlap the "Filter by product" section.

Tested on Firefox, Chrome & Safari browsers

![image](https://user-images.githubusercontent.com/28087895/228578819-3deef44e-f483-43e3-b964-688856080828.png)


Closing this ticket. Feel free to re-open if this is still reproducible for you

**Closed by emilghittasv** 2023-03-29 14:53 UTC
Labels: bug
