### ISSUE TITLE
Content of the Mozilla VPN-Get Help page is not wrapped at browser resize

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/sumo#1103] opened 2022-09-20 10:14 UTC
**Prerequisites:**
Be in Mozilla VPN [landing](https://www-dev.allizom.org/en-US/products/vpn/) or [download](https://www-dev.allizom.org/en-US/products/vpn/download/) page on a clean profile;

**Steps to reproduce:**
1. Click on the “Get Help” link;
2. Do a browser resize;
3. Observe SUMO page content;

**Expected results:**
Page content is wrapped;

**Actual results:**
Page content is partially wrapped.
![image-20220919-120330](https://user-images.githubusercontent.com/15685960/191231926-301e63b1-2e7e-4b10-887a-c7dc8747f342.png)

**Comment by emilghittasv** [comment] 2023-03-01 12:51
This seems to be a duplicate of https://github.com/mozilla/sumo/issues/960.

**Closed** 2023-03-01 12:51 UTC
Labels: bug
