### ISSUE TITLE
Update Thunderbird logo

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1610] opened 2023-12-07 08:49 UTC
More info https://bugzilla.mozilla.org/show_bug.cgi?id=1868623

**Comment by smithellis** [comment] 2024-02-12 15:41
Check this in production I guess? It was an admin change.

**Comment by smithellis** [comment] 2024-02-12 15:51
Logo from [here](https://design.thunderbird.net/resources/logo)

**Comment by emilghittasv** [comment] 2024-02-12 15:55
I can confirm that the new logo for Thunderbird is displayed in `prod`.

Verified while going through different pages of the AAQ, KB article, forum flows. 

Since this is already live in `prod` we can close this ticket directly.

**Closed as completed by emilghittasv** 2024-02-12 15:55 UTC
