### ISSUE TITLE
Remove Wagtail from the code-base

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2008] opened 2024-10-15 15:56 UTC

**Comment by akatsoulas** [comment] 2024-10-15 15:57
This will require a series of PRs in order to complete the removal. 
1st PR https://github.com/mozilla/kitsune/pull/6291

**Comment by akatsoulas** [comment] 2024-10-15 15:58
Other PRs will depend on merging https://github.com/mozilla/kitsune/pull/6291

**Comment by akatsoulas** [comment] 2024-10-16 14:49
[PR to squash](https://github.com/mozilla/kitsune/pull/6295) migrations from `sumo` and `products` apps.

**Comment by akatsoulas** [comment] 2024-11-01 11:20
~~PR to remove squashed migrations https://github.com/mozilla/kitsune/pull/6327~~

**Comment by akatsoulas** [comment] 2024-11-01 11:31
PR to remove traces of Wagtail https://github.com/mozilla/kitsune/pull/6328

**Comment by emilghittasv** [comment] 2024-11-06 13:11
General regression testing did not yield any issues caused by this change.

Moving this ticket inside the `release` column.

**Closed as completed** 2024-12-09 17:07 UTC
