### ISSUE TITLE
Add more checks before accepting a vote in KB

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1410] opened 2023-08-07 12:02 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1846719

**Comment by smithellis** [comment] 2024-01-02 22:32
Marked as fixed via https://github.com/mozilla/kitsune/pull/5703

**Comment by emilghittasv** [comment] 2024-01-04 10:20
I am unable to reproduce the issue mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1846719 using Burp Suite. The number of question votes cannot be incremented after voting more than once. 

I'm going to directly close this ticket since this issue was fixed a while back and it already lives inside `prod`.

**Closed by emilghittasv** 2024-01-04 10:20 UTC
